# Generated by Django 3.2a1 on 2022-05-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=240, null=True, verbose_name='client_name')),
                ('collection_title', models.CharField(max_length=400, verbose_name='collection_title')),
                ('roadshow_uuid', models.CharField(max_length=240, null=True, verbose_name='roadshow_uuid')),
                ('type', models.CharField(max_length=240, null=True, verbose_name='type')),
                ('due_date', models.CharField(max_length=240, null=True, verbose_name='due_date')),
                ('agents', models.JSONField(null=True)),
                ('clients', models.JSONField(null=True)),
                ('stats', models.JSONField(null=True)),
                ('requests', models.JSONField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.CharField(max_length=240, null=True, verbose_name='start_date')),
                ('mark_as_ready', models.BooleanField(default=False)),
                ('dr_opportunity_id', models.CharField(max_length=240, null=True, verbose_name='dr_opportunity_id')),
                ('dr_opportunity_code', models.CharField(max_length=240, null=True, verbose_name='dr_opportunity_code')),
                ('issuer_id', models.CharField(max_length=240, null=True, verbose_name='issuer_id')),
                ('external_storage', models.JSONField(null=True, verbose_name='external_storage')),
            ],
        ),
    ]
